.github/workflows/validate.yml, hacs.json
=> 🛒 HACS requirements

README.md, cheapest_energy_hours.jinja
Add `look_ahead` and `time_format` variables
=> 🕕 Add variables for time

README.md, cheapest_energy_hours.jinja, example_package/package.yaml
New approach to add weights to the prices.
Needs an array with weights per time period
=> ⚖ Refactor weights

cheapest_energy_hours.jinja, example_package/package.yaml
fixes:
* bugs introduces with new weight implementation
* bug in template sensor for weight plotting
=> 🐛 Bug fixes

README.md, example_package/README.md, example_package/package.yaml, example_package/script.yaml, example_package/sensor.yaml
* Completed plots will be recalculated to the lowest consumption in the list as base value (`1`)
* Added README for script and sensor
* Updated README for macro with some additional information
* Created separate files with script and sensor to make it easier to import them in your configuration
=> Improve script and template sensor

README.md, cheapest_energy_hours.jinja
Additional modes to show the time of the lowest and highest price within the selected list of hours
=> Add `time_min` and `time_max` modes

README.md, cheapest_energy_hours.jinja, example_package/README.md
This removes the need to set w and wp manually when you add `program='Your Description'` to the macro input.
=> Add shortcut `program`

README.md, cheapest_energy_hours.jinja
Creates a new output mode `split`
=> Add mode split

cheapest_energy_hours.jinja
* Fix bug which caused errors when no `mode` was provided
* Fix bug which caused errors when mode split was used and the sensor provided datetime strings
=> 🐛 Bugfixes

cheapest_energy_hours.jinja
If applicable the macro will output multiple error messages at ones, and error messages for invalid time key and value key have been added
=> Improve error message output

cheapest_energy_hours.jinja
=> Energy plot issue

cheapest_energy_hours.jinja
Add debug parameter which outputs a dict with information about the user input, changes by the macro and output
=> Add debug setting

README.md, documentation/1-source_sensor.md, documentation/2-basic_data.md, documentation/3-advanced_data.md
Ben tot 3 gekomen, moet nu weg. Kan kijken of ik later nog 4-6 kan reviewen voor je.
=> Docs review

cheapest_energy_hours.jinja, documentation/3-advanced_data.md, documentation/4-data_output.md
=> Add feature: Total expected costs based on weighted points

cheapest_energy_hours.jinja
=> Fix for extreme_now when current price is not included

documentation/4-data_output.md
Found some typo's while reading the docs.
=> Corrected typos in documentation/4-data_output

documentation/1-source_sensor.md
=> Fix issue with Omie template sensor for Portugal

documentation/1-source_sensor.md
=> Add Octopus Energy to Data Provider Settings overview

documentation/1-source_sensor.md
Add data provider settings for the custom integration Frank Energie to the documentation
fixes #201
=> Data provider settings for "FrankEnergie"

cheapest_energy_hours.jinja
Fixes #200
The weighted average was not calculated correctly, and the price tolerance wasn't applied in all cases. This is now fixed.
=> Fix calculation for `weighted_average` and `price_tolerance`
